name: local_express
description: "Local Express - On-Demand Delivery App for Vehari City"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.3.7

  # State Management
  provider: ^6.1.2
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1

  # UI & Animations
  lottie: ^3.1.3
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Navigation
  go_router: ^14.6.2

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0

  # Utilities
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  uuid: ^4.5.1

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.12
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: Urdu
  #     fonts:
  #       - asset: assets/fonts/NotoSansUrdu-Regular.ttf
  #       - asset: assets/fonts/NotoSansUrdu-Bold.ttf
  #         weight: 700
