echo "Testing Flutter installation..."
echo "Run these commands after manual installation:"
echo ""
echo "# Test if Flutter is accessible"
echo "flutter --version"
echo ""
echo "# Check Flutter setup"
echo "flutter doctor"
echo ""
echo "# Setup your Local Express project"
echo "cd \"C:\\Users\\Ahsan\\Desktop\\delivery\""
echo "flutter pub get"
echo "flutter doctor"
echo ""
echo "Expected result: Flutter version info should display"
