// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkRR1JwDgJmoYutAckg82b3aiaDpVTDk',
    appId: '1:199801881444:web:c5dbde6f5a5e5219483071',
    messagingSenderId: '199801881444',
    projectId: 'delivery-957cf',
    authDomain: 'delivery-957cf.firebaseapp.com',
    storageBucket: 'delivery-957cf.firebasestorage.app',
    measurementId: 'G-694P4PRNBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEkRR1JwDgJmoYutAckg82b3aiaDpVTDk',
    appId: '1:199801881444:android:c5dbde6f5a5e5219483071',
    messagingSenderId: '199801881444',
    projectId: 'delivery-957cf',
    authDomain: 'delivery-957cf.firebaseapp.com',
    storageBucket: 'delivery-957cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEkRR1JwDgJmoYutAckg82b3aiaDpVTDk',
    appId: '1:199801881444:ios:c5dbde6f5a5e5219483071',
    messagingSenderId: '199801881444',
    projectId: 'delivery-957cf',
    authDomain: 'delivery-957cf.firebaseapp.com',
    storageBucket: 'delivery-957cf.firebasestorage.app',
    iosBundleId: 'com.example.localExpress',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEkRR1JwDgJmoYutAckg82b3aiaDpVTDk',
    appId: '1:199801881444:ios:c5dbde6f5a5e5219483071',
    messagingSenderId: '199801881444',
    projectId: 'delivery-957cf',
    authDomain: 'delivery-957cf.firebaseapp.com',
    storageBucket: 'delivery-957cf.firebasestorage.app',
    iosBundleId: 'com.example.localExpress',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEkRR1JwDgJmoYutAckg82b3aiaDpVTDk',
    appId: '1:199801881444:web:c5dbde6f5a5e5219483071',
    messagingSenderId: '199801881444',
    projectId: 'delivery-957cf',
    authDomain: 'delivery-957cf.firebaseapp.com',
    storageBucket: 'delivery-957cf.firebasestorage.app',
    measurementId: 'G-694P4PRNBQ',
  );
}
